$('.form-login').submit(e=>{
    getToken()
        .then(result=>{
            localStorage.setItem("token",result.token);
            window.location.replace("./");
        })
        .catch(result=>{
            $(".error").html(result.responseJSON.message);
        })
    e.preventDefault();
})
checkLogin()
    .then(result=>{
        window.location.replace('./')
    });
$('#signup').click(e=>{
    window.location.replace('./signup')
})